#!/usr/bin/env php
<?php
/**
 * @param $url
 * @return mixed
 */
function get($url) {
    $ch = curl_init($url);
    curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
    curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
    curl_setopt($ch, CURLOPT_ENCODING, 'gzip');
    curl_setopt($ch, CURLOPT_USERAGENT, 'AlphaGo');

    $response = curl_exec($ch);
    curl_close($ch);

    return $response;
}

/**
 * @param $file
 * @param $destination
 */
function unzip_file($file, $destination) {
    $zip = new ZipArchive();

    if ($zip->open($file) !== TRUE) {
        die("Could not open archive");
    }

    $zip->extractTo($destination);

    $zip->close();
}

echo '正在安装云梯…' . PHP_EOL;

# 获取 last releases download url
$api_url = 'https://api.github.com/repos/springjk/test-yunti-speed/releases/latest';

$version = json_decode(get($api_url), true);

$file_url = $version['assets'][0]['browser_download_url'];

# 下载文件
file_put_contents(__DIR__ . '/test-yunti-speed.zip', get($file_url));

# 解压文件
unzip_file(__DIR__ . '/test-yunti-speed.zip', __DIR__);

unlink(__DIR__ . '/test-yunti-speed.zip');
# 添加全局执行
$command = 'rm /usr/local/bin/yunti && ln -s ' . __DIR__ . '/test-yunti-speed/yunti /usr/local/bin/yunti && chmod a+x /usr/local/bin/yunti';

exec($command);

echo '安装成功，命令 yunti 已链接到 /usr/local/bin/，你可以在任意位置运行 yunti 进行 vpn 连接。' . PHP_EOL;
